version: '3.8'

services:

 database:
  image: postgres
  ports:
   - 5432:5432
  environment:
   POSTGRES_PASSWORD: 'password'
   POSTGRES_USER: 'user'
   POSTGRES_DB: 'realities'

 scraper:
  build: scraper/
  environment:
    POSTGRES_HOST: database
    POSTGRES_PORT: '5432'
    POSTGRES_USER: 'user'
    POSTGRES_PASS: 'password'
    POSTGRES_DB: 'realities'
  depends_on:
    - database

 server:
    build: server/
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: '5432'
      POSTGRES_USER: 'user'
      POSTGRES_PASS: 'password'
      POSTGRES_DB: 'realities'
